apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: 775826428475.dkr.ecr.ap-south-1.amazonaws.com/order:latest
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: order-config