apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 775826428475.dkr.ecr.ap-south-1.amazonaws.com/auth:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: auth-config