apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 775826428475.dkr.ecr.ap-south-1.amazonaws.com/cart:latest
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: cart-config