apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: backend
data:
  DB_HOST: "<RDS_ENDPOINT>"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "12345678"

  JWT_SECRET: "014ffc23305636ca26ee50d7dc56768c7ecbab7f7c9478f262d5591d2aacd5bf193ebbf6b77ccf462811f50588b90396ef58e62dad23e82e3f127e0d54964f23"
  JWT_EXPIRES_IN: "7d"
  AWS_REGION : "us-east-1"
  S3_BUCKET_NAME: "devops project-frontend"

  PORT: "5004"
  NODE_ENV: "production"
  SEED_USERS: "true"