apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
  namespace: backend
data:
  PORT: "5006"
  NODE_ENV: "production"

  # Email Configuration
  EMAIL_USER: "rajesha100920@gmail.com"
  EMAIL_PASSWORD: "ijkl rtny jycm bvjc"

  # Test Email
  TEST_EMAIL: "rark21ec@cmrit.ac.in"

  # JWT Secret
  JWT_SECRET: "014ffc23305636ca26ee50d7dc56768c7ecbab7f7c9478f262d5591d2aacd5bf193ebbf6b77ccf462811f50588b90396ef58e62dad23e82e3f127e0d54964f23"