apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: <ECR_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/auth:latest
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets