apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: <ECR_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/cart:latest
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets