apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/devops-project-email:latest
        ports:
        - containerPort: 5006
        env:
        - name: PORT
          value: "5006"
        - name: NODE_ENV
          value: "production"
        - name: EMAIL_USER
          value: "rajesha100920@gmail.com"
        - name: EMAIL_PASSWORD
          value: "ijkl rtny jycm bvjc"
        - name: TEST_EMAIL
          value: "rark21ec@cmrit.ac.in"
        - name: JWT_SECRET
          value: "014ffc23305636ca26ee50d7dc56768c7ecbab7f7c9478f262d5591d2aacd5bf193ebbf6b77ccf462811f50588b90396ef58e62dad23e82e3f127e0d54964f23"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5006
          initialDelaySeconds: 30
          periodSeconds: 10