apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: <ECR_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/order:latest
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets