apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: <ECR_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/payment:latest
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets