apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: <ECR_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/product:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets