apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/devops-project-product:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "YOUR_RDS_ENDPOINT"  # Will be replaced by Jenkins
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "12345678"
        - name: JWT_SECRET
          value: "014ffc23305636ca26ee50d7dc56768c7ecbab7f7c9478f262d5591d2aacd5bf193ebbf6b77ccf462811f50588b90396ef58e62dad23e82e3f127e0d54964f23"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10