apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: backend
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP