apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: backend
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP