apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: backend
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP